version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app_service
    volumes:
      - type: volume
        source: app-vol
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./projects/${CLUSTER}/${APP_SRC}
        target: /work/project
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    depends_on:
      - mysql
    networks:
      - lara_nat
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx_service
    ports:
      - target: 80
        published: 80
    volumes:
      - type: volume
        source: app-vol
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./projects/${CLUSTER}/${APP_SRC}
        target: /work/project
    networks:
      - lara_nat
  # db:
  #   container_name: pg_db_service
  #   image: "postgres:12"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./projects/${CLUSTER}/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=postgres
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   networks:
  #     - lara_nat

  mysql:
    image: bitnami/mysql:5.7
    volumes:
      - ./projects/${CLUSTER}/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=laravel
    networks:
      - lara_nat

  redis:
    image: redis:latest
    container_name: cache_service
    volumes:
      - redis-store:/data
    ports:
      - 6379:6379
    networks:
      - lara_nat
networks:
  lara_nat:
    driver: bridge
volumes:
  app-vol:
  db-store:
  psysh-store:
  redis-store:
